const $ = id => document.getElementById(id);
const state = { ctx:null, buffer:null, source:null, playing:false, startedAt:0, offset:0, duration:0, data:null, file:null, enhance:false, window:24, depth:1.4, raf:0 };
const els = ['fileInput','heroInput','playBtn','backBtn','forwardBtn','seekRange','currentTime','duration','clock','speed','volume','loopBtn','overview','overviewCanvas','playhead','emptyState','overviewEmpty','fileName','fileMeta','enhanceToggle','originalBtn','enhancedBtn','strength','clarity','noise','voiceGain','windowRange','depthRange','resetView','glCanvas'].reduce((o,k)=>(o[k]=$(k),o),{});
const fmt = (s, ms=false) => { s=Math.max(0,s||0); const h=Math.floor(s/3600),m=Math.floor(s%3600/60),sec=Math.floor(s%60); return `${h?String(h).padStart(2,'0')+':':''}${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}${ms?'.'+String(Math.floor(s%1*1000)).padStart(3,'0'):''}` };
const db = v => v > 0 ? 20*Math.log10(v) : -90;

class AudioEngine {
  async load(file){ this.stop(); state.ctx ||= new (window.AudioContext||window.webkitAudioContext)({latencyHint:'interactive'}); const bytes=await file.arrayBuffer(); state.buffer=await state.ctx.decodeAudioData(bytes); state.duration=state.buffer.duration; state.offset=0; this.buildGraph(); }
  buildGraph(){const c=state.ctx; this.input=c.createGain();this.dry=c.createGain();this.wet=c.createGain();this.hp=c.createBiquadFilter();this.hp.type='highpass';this.hp.frequency.value=85;this.low=c.createBiquadFilter();this.low.type='lowshelf';this.low.frequency.value=240;this.pres=c.createBiquadFilter();this.pres.type='peaking';this.pres.frequency.value=2600;this.pres.Q.value=.75;this.comp=c.createDynamicsCompressor();this.comp.threshold.value=-28;this.comp.knee.value=15;this.comp.ratio.value=3.2;this.comp.attack.value=.009;this.comp.release.value=.18;this.makeup=c.createGain();this.limiter=c.createDynamicsCompressor();this.limiter.threshold.value=-2;this.limiter.knee.value=0;this.limiter.ratio.value=20;this.limiter.attack.value=.002;this.limiter.release.value=.08;this.analyser=c.createAnalyser();this.analyser.fftSize=2048;this.analyser.smoothingTimeConstant=.72;this.master=c.createGain();this.input.connect(this.dry).connect(this.analyser);this.input.connect(this.hp).connect(this.low).connect(this.pres).connect(this.comp).connect(this.makeup).connect(this.limiter).connect(this.wet).connect(this.analyser);this.analyser.connect(this.master).connect(c.destination);this.updateDSP();}
  updateDSP(){if(!this.wet)return;const on=state.enhance,s=+els.strength.value/100,n=+els.noise.value/100,cl=+els.clarity.value/100,g=+els.voiceGain.value;this.dry.gain.setTargetAtTime(on?0:1,state.ctx.currentTime,.012);this.wet.gain.setTargetAtTime(on?1:0,state.ctx.currentTime,.012);if(!on)this.input.gain.setTargetAtTime(1,state.ctx.currentTime,.012);this.low.gain.value=-2-4*s;this.pres.gain.value=1+7*cl;this.comp.threshold.value=-20-18*s;this.comp.ratio.value=2+3*s;this.makeup.gain.value=Math.pow(10,(g+3*s)/20);this.gateThreshold=.004+n*.018}
  play(){if(!state.buffer||state.playing)return;state.ctx.resume();const s=state.ctx.createBufferSource();s.buffer=state.buffer;s.playbackRate.value=this.rate();s.loop=els.loopBtn.classList.contains('active');s.connect(this.input);s.onended=()=>{if(state.playing&&!s.loop&&this.time()>=state.duration-.05){state.playing=false;state.offset=state.duration;syncButton()}};state.source=s;state.startedAt=state.ctx.currentTime;state.playing=true;s.start(0,state.offset);syncButton()}
  pause(){if(!state.playing)return;state.offset=this.time();state.playing=false;try{state.source.stop()}catch{}syncButton()}
  stop(){if(state.playing)this.pause();state.offset=0}
  seek(t){const was=state.playing;if(was)this.pause();state.offset=Math.max(0,Math.min(state.duration||0,t));if(was)this.play();drawFrame()}
  time(){if(!state.playing)return state.offset;let t=state.offset+(state.ctx.currentTime-state.startedAt)*this.rate();if(els.loopBtn.classList.contains('active')&&state.duration)t%=state.duration;return Math.min(t,state.duration)}
  rate(){return parseFloat(els.speed.value)||1}
  setRate(){const was=state.playing,t=this.time();if(was)this.pause();state.offset=t;if(was)this.play()}
}
const audio=new AudioEngine();

class SpectralView {
  constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext('webgl',{antialias:true,alpha:true,powerPreference:'high-performance'});this.yaw=-.56;this.pitch=.64;this.zoom=1;this.pan=0;this.drag=null;this.touches=0;this.init();this.events()}
  init(){const g=this.gl;if(!g)return;const vs=`attribute vec3 p;attribute float a;uniform mat4 m;varying float v;void main(){v=a;gl_Position=m*vec4(p,1.);gl_PointSize=2.;}`;const fs=`precision mediump float;varying float v;void main(){vec3 c=mix(vec3(.03,.19,.18),mix(vec3(.19,.88,.68),vec3(.69,.43,.93),smoothstep(.5,1.,v)),v);gl_FragColor=vec4(c,.28+v*.72);}`;const sh=(t,s)=>{const x=g.createShader(t);g.shaderSource(x,s);g.compileShader(x);return x};this.prog=g.createProgram();g.attachShader(this.prog,sh(g.VERTEX_SHADER,vs));g.attachShader(this.prog,sh(g.FRAGMENT_SHADER,fs));g.linkProgram(this.prog);this.buf=g.createBuffer();this.count=0}
  events(){const c=this.canvas;c.addEventListener('pointerdown',e=>{c.setPointerCapture(e.pointerId);this.drag=[e.clientX,e.clientY,e.pointerId]});c.addEventListener('pointermove',e=>{if(!this.drag||this.drag[2]!==e.pointerId)return;const dx=e.clientX-this.drag[0],dy=e.clientY-this.drag[1];this.yaw+=dx*.008;this.pitch=Math.max(.1,Math.min(1.35,this.pitch+dy*.008));this.drag=[e.clientX,e.clientY,e.pointerId];this.draw()});c.addEventListener('pointerup',()=>this.drag=null);c.addEventListener('wheel',e=>{e.preventDefault();this.zoom=Math.max(.5,Math.min(3,this.zoom*Math.exp(-e.deltaY*.001)));this.draw()},{passive:false});let dist=0;c.addEventListener('touchmove',e=>{if(e.touches.length===2){const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);if(dist)this.zoom=Math.max(.5,Math.min(3,this.zoom*d/dist));dist=d;this.draw()}},{passive:false});c.addEventListener('touchend',()=>dist=0)}
  reset(top=false){this.yaw=top?0:-.56;this.pitch=top?1.48:.64;this.zoom=1;this.draw()}
  update(){if(!state.data)return;const {spectrum,bins}=state.data, cols=Math.min(200,Math.floor(this.canvas.clientWidth/4)), center=Math.floor(audio.time()/state.duration*(spectrum.length/bins));const total=spectrum.length/bins, windowCols=Math.max(10,Math.floor(state.window/state.duration*total));const start=Math.max(0,center-windowCols*.48),arr=[];for(let x=0;x<cols;x++){const ci=Math.min(total-1,Math.floor(start+x/cols*windowCols));for(let y=0;y<bins;y++){const amp=spectrum[ci*bins+y]/255;arr.push(x/(cols-1)*2-1,(y/(bins-1)*2-1),amp*state.depth-.7,amp)}}this.vertices=new Float32Array(arr);const g=this.gl;if(g){g.bindBuffer(g.ARRAY_BUFFER,this.buf);g.bufferData(g.ARRAY_BUFFER,this.vertices,g.DYNAMIC_DRAW);this.count=arr.length/4}this.draw()}
  draw(){const g=this.gl;if(!g||!this.count)return;const d=devicePixelRatio||1,w=this.canvas.clientWidth*d,h=this.canvas.clientHeight*d;if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h}g.viewport(0,0,w,h);g.clearColor(0,0,0,0);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);g.enable(g.DEPTH_TEST);g.enable(g.BLEND);g.blendFunc(g.SRC_ALPHA,g.ONE_MINUS_SRC_ALPHA);g.useProgram(this.prog);const cy=Math.cos(this.yaw),sy=Math.sin(this.yaw),cp=Math.cos(this.pitch),sp=Math.sin(this.pitch),z=.62*this.zoom,aspect=h/w;const m=new Float32Array([cy*z,sy*sp*z*aspect,-sy*cp,0, -sy*z,cy*sp*z*aspect,-cy*cp,0,0,cp*z*aspect,sp,0,0,-.05,0,1]);g.uniformMatrix4fv(g.getUniformLocation(this.prog,'m'),false,m);g.bindBuffer(g.ARRAY_BUFFER,this.buf);const p=g.getAttribLocation(this.prog,'p'),a=g.getAttribLocation(this.prog,'a');g.enableVertexAttribArray(p);g.vertexAttribPointer(p,3,g.FLOAT,false,16,0);g.enableVertexAttribArray(a);g.vertexAttribPointer(a,1,g.FLOAT,false,16,12);g.drawArrays(g.POINTS,0,this.count);g.disable(g.DEPTH_TEST);g.drawArrays(g.LINE_STRIP,0,this.count)}
}
const view=new SpectralView(els.glCanvas);

async function loadFile(file){if(!file)return;try{$('renderStatus').textContent='DECODING AUDIO';els.fileName.textContent=file.name;els.fileMeta.textContent='Decoding locally…';await audio.load(file);state.file=file;els.duration.textContent=fmt(state.duration);els.seekRange.max=state.duration;els.playBtn.disabled=false;els.emptyState.classList.add('hidden');els.overviewEmpty.style.display='none';els.fileMeta.textContent=`${fmt(state.duration)} · ${(file.size/1048576).toFixed(1)} MB · ${Math.round(state.buffer.sampleRate/1000)} kHz`;const src=state.buffer.getChannelData(0);const copy=new Float32Array(src);const worker=new Worker('fft-worker.js');worker.onmessage=e=>{state.data=e.data;worker.terminate();drawOverview();view.update();$('renderStatus').textContent='GPU VIEW READY'};worker.onerror=()=>{$('renderStatus').textContent='ANALYSIS ERROR'};worker.postMessage({samples:copy,sampleRate:state.buffer.sampleRate,columns:Math.min(1400,Math.max(600,Math.floor(state.duration*.7))),bins:48},[copy.buffer])}catch(err){console.error(err);els.fileMeta.textContent='Could not decode this format';$('renderStatus').textContent='UNSUPPORTED AUDIO'}}
function drawOverview(){const c=els.overviewCanvas,d=devicePixelRatio||1,w=c.clientWidth*d,h=c.clientHeight*d;c.width=w;c.height=h;const x=c.getContext('2d'),{waveform,activity,spectrum,bins}=state.data;x.clearRect(0,0,w,h);for(let i=0;i<w;i++){const ci=Math.floor(i/w*waveform.length);for(let b=0;b<bins;b++){const a=spectrum[ci*bins+b]/255;if(a>.05){x.fillStyle=`rgba(${40+a*40},${120+a*110},${125+a*70},${a*.32})`;x.fillRect(i,h-(b+1)/bins*h,1,h/bins+1)}}}x.lineWidth=1.5*d;x.strokeStyle='#55e8b1';x.beginPath();for(let i=0;i<w;i++){const ci=Math.floor(i/w*waveform.length),amp=waveform[ci]*h*.32;x.moveTo(i,h*.5-amp);x.lineTo(i,h*.5+amp)}x.stroke();for(let i=0;i<w;i++){const ci=Math.floor(i/w*activity.length);if(activity[ci]>.32){x.fillStyle=`rgba(86,232,177,${activity[ci]*.18})`;x.fillRect(i,h-8*d,1,8*d)}}}
function syncButton(){els.playBtn.textContent=state.playing?'Ⅱ':'▶';els.playBtn.setAttribute('aria-label',state.playing?'Pause':'Play')}
function seekFromEvent(e){const r=els.overview.getBoundingClientRect(),x=(e.touches?.[0]?.clientX??e.clientX)-r.left;audio.seek(x/r.width*state.duration)}
function metrics(t){if(!state.data)return;const {activity,rms,spectrum,bins}=state.data,idx=Math.min(activity.length-1,Math.floor(t/state.duration*activity.length)),prob=Math.round(activity[idx]*100),r=rms[idx],base=idx*bins;let max=0,bi=0;for(let b=0;b<bins;b++)if(spectrum[base+b]>max){max=spectrum[base+b];bi=b}const ny=Math.min(12000,state.buffer.sampleRate/2),freq=Math.round(70*Math.pow(ny/70,bi/(bins-1)));$('speechMetric').textContent=prob;$('probRing').style.background=`conic-gradient(var(--mint) ${prob*3.6}deg,#243331 0)`;$('speechLabel').textContent=prob>45?'Speech-like signal':'Ambient / silence';$('voiceStatus').textContent=prob>45?'VOICE DETECTED':'AMBIENT';$('voiceStatus').classList.toggle('detected',prob>45);$('freqMetric').textContent=freq;$('peakMetric').textContent=Math.max(-90,db(state.data.waveform[idx])).toFixed(1);$('rmsMetric').textContent=Math.max(-90,db(r)).toFixed(1);if(state.enhance&&audio.input){const target=r<(audio.gateThreshold||0)?0.22:1;audio.input.gain.setTargetAtTime(target,state.ctx.currentTime,.04)}}
let lastView=0;function drawFrame(now=0){const t=audio.time();els.currentTime.textContent=fmt(t);els.clock.textContent=fmt(t,true);els.seekRange.value=t;if(state.duration){els.playhead.style.display='block';els.playhead.style.left=`${t/state.duration*100}%`}metrics(t);if(now-lastView>250){view.update();lastView=now}if(state.playing)state.raf=requestAnimationFrame(drawFrame)}

[els.fileInput,els.heroInput].forEach(x=>x.addEventListener('change',e=>loadFile(e.target.files[0])));els.playBtn.onclick=()=>{state.playing?audio.pause():audio.play();cancelAnimationFrame(state.raf);drawFrame();if(state.playing)state.raf=requestAnimationFrame(drawFrame)};els.backBtn.onclick=()=>audio.seek(audio.time()-10);els.forwardBtn.onclick=()=>audio.seek(audio.time()+10);els.seekRange.oninput=e=>audio.seek(+e.target.value);els.overview.addEventListener('pointerdown',seekFromEvent);els.speed.onchange=()=>audio.setRate();els.volume.oninput=e=>{if(audio.master)audio.master.gain.value=+e.target.value};els.loopBtn.onclick=()=>{els.loopBtn.classList.toggle('active');els.loopBtn.setAttribute('aria-pressed',els.loopBtn.classList.contains('active'))};
function setEnhance(on){state.enhance=on;els.enhanceToggle.checked=on;els.originalBtn.classList.toggle('active',!on);els.enhancedBtn.classList.toggle('active',on);$('enhanceMetric').textContent=on?'ON':'OFF';audio.updateDSP()}
els.enhanceToggle.onchange=e=>setEnhance(e.target.checked);els.originalBtn.onclick=()=>setEnhance(false);els.enhancedBtn.onclick=()=>setEnhance(true);for(const [id,out,format] of [['strength','strengthOut',v=>v+'%'],['clarity','clarityOut',v=>v+'%'],['noise','noiseOut',v=>v+'%'],['voiceGain','gainOut',v=>(v>=0?'+':'')+(+v).toFixed(1)+' dB']])els[id].oninput=e=>{ $(out).textContent=format(e.target.value);audio.updateDSP()};els.windowRange.oninput=e=>{state.window=+e.target.value;$('windowOut').textContent=state.window+' sec';view.update()};els.depthRange.oninput=e=>{state.depth=+e.target.value/10;$('depthOut').textContent=state.depth.toFixed(1)+'×';view.update()};els.resetView.onclick=()=>view.reset();document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));view.reset(b.dataset.view==='top')});window.addEventListener('resize',()=>{if(state.data){drawOverview();view.update()}});document.addEventListener('keydown',e=>{if(e.code==='Space'&&!/INPUT|SELECT/.test(e.target.tagName)){e.preventDefault();els.playBtn.click()}if(e.code==='ArrowLeft')audio.seek(audio.time()-10);if(e.code==='ArrowRight')audio.seek(audio.time()+10)});
