onlyBuiltDependencies:
  - unrs-resolver
minimumReleaseAge: 4320
minimumReleaseAgeIgnoreMissingTime: false
blockExoticSubdeps: true
trustLockfile: false
strictDepBuilds: true
engineStrict: true
saveExact: true
strictPeerDependencies: true
